---
# Environment
environment:
  stage: "DEVELOPMENT" # LOCAL, DEVELOPMENT, TEST, STAGING, PRODUCTION
  runTestEnvironment: ["LOCAL", "DEVELOPMENT", "TEST"]

# Databases
databases:
  identityDB:
    connectionName: "db-identity"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "d3ta"
    password: "d3ta"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "a_d3ta_iam"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production
  emailDB:
    connectionName: "db-email"
    driver: "mysql" # mysql, postgres, sqlserver, sqlite3
    # mysql
    username: "d3ta"
    password: "d3ta"
    hostName: "127.0.0.1:3306" # hostname:port OR path
    dbName: "a_d3ta_email"
    config: "charset=utf8&parseTime=True&loc=Local"
    maxIdleConns: 10
    maxOpenConns: 10
    logMode: true # shoud be "false" on production

# Directory Locations
dirLocations:
  conf: "./conf"
  www: "./www"
  temp: "./temp"
  log: "./logs"
  cache: "./caches"

# SMTP Servers
SMTPServers:
  defaultSMTP:
    server: "smtp.gmail.com"
    port: "587"
    username: "email@gmail.com"
    password: "password"
    senderEmail: "no-reply@gmail.com"
    senderName: "D3TAgo NoReply"

# Caches
caches:
  # Cache with Redis engine Sample
  sessionCache:
    connectionName: "session-cache"
    engine: "redis"
    driver: "redis"
    configurations: # Following redis engine
      network: "tcp"
      host: "127.0.0.1"
      port: "6379"
      username: ""
      password: ""
      db: 1
      maxRetries: 3
      poolSize: 10
      minIdleConns: 5
  # Cache with GoMacaron/Cache engine Sample
  tmpDataCache:
    connectionName: "tmp-data-cache"
    engine: "gomacaron"
    driver: "redis"
    configurations: # Following GoMacaron/Cache engine
      adapter: "redis"
      adapterConfig: "addr:127.0.0.1:6379"
      interval: 60
      occupyMode: false
      section: "cache"
